### ISSUE TITLE
Document .tree_fields() (was: Providing queryset in `ancestors`)

### ISSUE THREAD

**Issue by saveshodhan** [feincms/django-tree-queries#76]
Hello,

I have a usecase in which I fetch multiple leaf-nodes, and each of them need to display their `ancestors` (including self).
There is this method - [ancestors](https://github.com/feincms/django-tree-queries/blob/main/tree_queries/query.py#L98) that does this, but if we have multiple nodes then this results into those many hits to the DB.

I am thinking, if we make a provision to accept a queryset in this method, the method can just use it rather than hitting the db each time. Wdyt?

Currently i implemented a custom method that does the same thing, but it would be really cool to have this baked into the library itself.

If you think this is a good idea I can also take it up and submit a PR..

Thanks!

**Comment by matthiask** [comment]
Hi,

I'm not 100% sure what you're proposing, can you show an example? 

Also, have you seen the `.tree_fields()` function tested here? https://github.com/feincms/django-tree-queries/blob/9b3af54bfe4ea0d25db776f9ce9c9d48f88a96ce/tests/testapp/test_queries.py#L994-L1014  Maybe this already does what you need?

**Comment by saveshodhan** [comment]
ah you are right! `tree_names` worked for me!! :pray:

**Comment by matthiask** [comment]
Nice! I'll keep this open because `tree_fields()` should be mentioned somewhere in the README.
